# Check on http://lint.travis-ci.org/ after modifying! Taken and modified
# from https://github.com/biocore/scikit-bio/blob/master/.travis.yml
sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n st2 python=$PYTHON_VERSION nose numpy scipy h5py flake8 scikit-bio=0.4.0
  - source activate st2
  - pip install coveralls
  - pip install .
script:
  - nosetests --with-coverage
  - flake8 sourcetracker setup.py
  - sourcetracker2 gibbs --help
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/map.txt -o example1/
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/alt-map.txt -o example2/ --source_sink_column source-or-sink --source_column_value src --sink_column_value snk --source_category_column sample-type
after_success:
  - coveralls
